services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/base:bookworm
    volumes:
      - ..:/workspace:cached
    command: sleep infinity

  plantuml:
    image: plantuml/plantuml-server:latest
    # https://plantuml.com/security
    environment:
      - PLANTUML_SECURITY_PROFILE=UNSECURE
    ports:
      - 9090:8080
